#!/bin/bash
echo "🚀 Quick Start iOS Real Device Testing"
echo "======================================"
echo ""
echo "1. Make sure your iPhone is connected via USB"
echo "2. Trust the computer on your iPhone if prompted"
echo "3. Run: ./one_command_ios_test.sh"
echo ""
echo "Or manually:"
echo "1. Start Appium: appium --log appium.log --log-level debug"
echo "2. Run test: poetry run python test_ios_real_device.py"
echo ""
echo "Configuration files:"
echo "- appium_config_ios_real_device.json (for Appium Inspector)"
echo "- test_ios_real_device.py (Python test script)"
